AppBundle\Entity\Conference:
  type:  entity
  table: conference
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 200
    start_time:
      type: datetime
    end_time:
      type: datetime
    call_for_papers_start:
      type: datetime
    call_for_papers_end:
      type: datetime
    paper_submission_start:
      type: datetime
    paper_submission_end:
      type: datetime
  manyToMany:
    paperTypes:
      targetEntity: AppBundle\Entity\PaperType
      inversedBy: conferences
      joinTable:
        name: papertype_conference
        joinColumns:
          conference_id:
            referencedColumnName: id
        inverseJoinColumns:
          paper_type_id:
            referencedColumnName: id