AppBundle\Entity\PaperType:
  type:  entity
  table: paper_type
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 200
  manyToMany:
    conferences:
      targetEntity: AppBundle\Entity\Conference
      mappedBy: paperTypes