AppBundle\Entity\Paper:
  type:  entity
  table: paper
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    title:
      type: string
      length: 200
    description:
      type: text
    file_name:
      type: string
      length: 200
      options:
        nullable: true
        default: null
    updated_at:
      type: datetime
  manyToOne:
    user:
      targetEntity: AppBundle\Entity\User
      inversedBy: papers
      joinColumn:
        name: user_id
        referencedColumnName: id
  oneToMany:
    paperEvaluations:
      targetEntity: PaperEvaluation
      mappedBy: paper
  oneToOne:
    paperType:
      targetEntity: PaperType
      joinColumn:
        name: paper_type_id
        referencedColumnName: id
      nullable: false