AppBundle\Entity\PaperEvaluation:
  type:  entity
  table: paper_evaluation
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    message:
      type: text
    rate:
      type: integer
  manyToOne:
    paper:
      targetEntity: AppBundle\Entity\Paper
      inversedBy: paperEvaluations
      joinColumn:
        name: paper_id
        referencedColumnName: id
    user:
      targetEntity: AppBundle\Entity\User
      inversedBy: paperEvaluations
      joinColumn:
        name: user_id
        referencedColumnName: id

