AppBundle\Entity\User:
  type:  entity
  table: fos_user
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    first_name:
      type: string
      length: 200
    last_name:
      type: string
      length: 200
  oneToMany:
    papers:
      targetEntity: Paper
      mappedBy: paper
    paperEvaluations:
      targetEntity: PaperEvaluation
      mappedBy: paper_evaluation
  manyToMany:
    conferences:
      targetEntity: Conference
      joinTable:
        name: users_conferences
        joinColumns:
          user_id:
            referencedColumnName: id
        inverseJoinColumns:
          conference_id:
            referencedColumnName: id