AppBundle\Entity\User:
  type:  entity
  table: fos_user
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    first_name:
      type: string
      length: 200
    last_name:
      type: string
      length: 200
    customer:
      type: string
      length: 200
      nullable: true
  oneToMany:
    papers:
      targetEntity: Paper
      mappedBy: user
    fullPapers:
      targetEntity: AppBundle\Entity\FullPaper
      mappedBy: user
    paperEvaluations:
      targetEntity: PaperEvaluation
      mappedBy: user
  manyToMany:
    conferences:
      targetEntity: Conference
      joinTable:
        name: users_conferences
        joinColumns:
          user_id:
            referencedColumnName: id
        inverseJoinColumns:
          conference_id:
            referencedColumnName: id